name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs para atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Snake Animation
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: raphaella220046
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Set output variables
        run: echo "SNAKE_GIF=${{ steps.snake-gif.outputs.file }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
